### ISSUE TITLE
always failed at 	err = unix.Connect(s, remoteSocket)

### ISSUE THREAD

**Issue by jannson** [elico/go-linux-tproxy#1]
Do you have any document about your project?
I have read your codes, but I don't understand, Thanks.
Now I always fail a go-linux-tproxy.go:200

**Comment by elico** [comment]
@jannson Hey, I do not have any special document since it's an advanced subject. While I am not that expert I do not understand where do you get the error from since my code doesn't have line 200 in it..
But you should know that the code requires couple things from the linux kernel.
If you can gist some of your code and also the details about your linux machine it would be pretty good to understand it.

**Comment by jannson** [comment]
Sorry, I changed your code and I forgot it. I will test it again in a VPS and give your more information about my environment.
Thank you for reply.

**Comment by elico** [comment]
@jannson Depends on your VPS you might not have the required kernel modules for example AWS Linux doesn't have anything that supports tproxy but you can use Ubuntu on AWS which contains tproxy support.
For other providers you would need to verify the list of modules or kernel core to know that.
You can use "panic(err)" and print the backtrace and with this output I might be able to understand it a bit more.

Also if you can share the changes you have made it would maybe help others.

**Comment by jannson** [comment]
Of course, If I fix some bugs and make it work, I will share all about code. But now I just use your code, and I don't understand more about tproxy, so it can not work now. I think your code is ok.
My big goal is make udp redirect  work in tproxy by using golang, then my ps4 can use a tranparent udp proxy to play games.
Now I am creating a VPS in linode using ubuntu. I will check it out later.

**Comment by jannson** [comment]
My evironment:
A: The server running tcpproxy1, ip: 198.58.105.220, ubuntu 14.04, linode, golang 1.5.2 from official website
B: The client just for test, centos 6.4

Idea of test is:
1. Run a tcp echo server at A by 198.58.105.220:8080, any connection to the echo server, the echo server will print information of connection
2. Catch all :8080 to tproxy by command: iptables -t mangle -A PREROUTING -p tcp --dport 8080 -j TPROXY --tproxy-mark 0x1/0x1 --on-port 9090
3. tcpproxy1 run at 198.58.105.220:8080
4. setup a http_proxy at B and use curl to request, than request will connect to  198.58.105.220:8080, which catch by tproxy, then tcpproxy1 send request to echo server, at last echo server print the info of connection.

B:
export http_proxy=http://198.58.105.220:8080
curl -XGET http://aria2.me

echo server is: https://gist.github.com/jannson/26cbc1f03e3ae0dc0545

tproxy.sh: 
echo 1 >/proc/sys/net/ipv4/ip_forward 
iptables -t mangle -N DIVERT
iptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -j ACCEPT
ip rule add fwmark 1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -A PREROUTING -p tcp --dport 8080 -j TPROXY --tproxy-mark 0x1/0x1 --on-port 9090

Steps :
Run tproxy at A host
Run echo server
Run tcpproxy1
Set http_proxy at B host and make request

The log of A:
root@li562-220:~/workspace-go/src/github.com/elico/go-linux-tproxy/examples# ./tcpproxy1 -d=1 -l=:9090
Maximum FD per process: {1024 4096}
starting connection from: 183.17.252.205:41561, to: 198.58.105.220:8080
Before peeking

216
This is probably a PROXY connection
After peeking
183.17.252.205:41561
198.58.105.220:8080

starting connection from: 183.17.252.205:41571, to: 198.58.105.220:8080
Before peeking
connection timed out
remote dial failed: %v
 connection timed out

echo server has nothing log, means that nothing connection is request to echo server.

**Comment by jannson** [comment]
The timed out maybe occur at line of go-linux-tproxy.go
180         err = unix.Connect(s,remoteSocket)

Please give me your email, and my email is: gandancing@gmail.com
I'll send you my root/password of the linode server, if you need it for more information.
Thanks for your great project ^.^

**Comment by elico** [comment]
I will send you an email.. but it is not clear to me yet why are you using tproxy?

**Comment by jannson** [comment]
Check your email please :)

**Comment by jannson** [comment]
My test is wrong, and here is some information:
http://wiki.squid-cache.org/ConfigExamples/UbuntuTproxy4Wccp2
