### ISSUE TITLE
Is this program available? Why do I always get stuck in unix.Connect(), and then the connection always times out.

### ISSUE THREAD

**Issue by ruinstoriel** [elico/go-linux-tproxy#2]
https://github.com/elico/go-linux-tproxy/blob/125addb82a45fb475f9fe7602b4d6b698be13174/go-linux-tproxy.go#L205

I am using an ubuntu system, and my situation is very similar to #1, but I do not use any Squid programs. And #1 doesn't provide any more useful information.
When I delete unix.bind and its related code, the program works normally.

**Comment by ruinstoriel** [comment]
If the requested network segment and the tproxy server are not in the same network segment, the target server must at least be able to obtain the original address and correctly route to the tproxy server. If they are on the same network segment, it is possible to route the traffic directly to the client without going through the tproxy server.

**Comment by elico** [comment]
@ruinstoriel It's not clear from your information enough to understand what are we talking about.
I need more details to understand the issue and let you know what is the best path.

**Comment by ruinstoriel** [comment]
@elico  When I figured out the principles, it became very simple. But we should still pay attention when doing tests. When using the gre tunnel, the tproxy server dials up using the client's IP. When this IP is connected to the target server, if the target server cannot correctly route to the client IP, the connect will only time out. This is very simple, but we often don't think that some hints should be given in the documentation, such as comments in the iptables script. like 'ip route add 10.80.2.0 via tproxyip' in the target server.
